import React from 'react'

const DancingText = () => {
  return (
    <div class="dancing-animation-container">
      <p>
        NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER NAROTTAM SINGH BISHT | SOFTWARE ENGINEER | CODER | TRAVELLER
    </p>
    </div >
  )
}

export default DancingText
